### ISSUE TITLE
examples for client and server

### ISSUE THREAD

**Issue by vtolstov** [frostschutz/go-nbd#1]
Hello. Can you provide some examples for client and server?

**Comment by frostschutz** [comment]
It's an unfinished project, sorry; I intend to pick this up again soon so it can be used as a block device in user space (so it implements the kernel interface of NBD). I have no plans for implementing NBD as in the network protocol that can talk to arbitrary clients/servers over the network.

**Comment by vtolstov** [comment]
Hm.. I want to use you project for writing custom nbd client and server that uses udp for transport.
As i understand server opens file for RW , listens network and doing read/write on RW device.
Client connect to server, create socket pair and pass it to kernel nbd, does this right?
